nodeLinker: node-modules

packageExtensions:
  "@devtools-ds/themes@*":
    dependencies:
      react-dom: ^18.0.0
  "@storybook/addon-docs@*":
    dependencies:
      "@babel/core": "*"
      webpack: "*"
  "@storybook/docs-tools@*":
    dependencies:
      react: ^18.0.0
      react-dom: ^18.0.0
  "@storybook/instrumenter@*":
    dependencies:
      react: ^18.0.0
      react-dom: ^18.0.0
  "@storybook/mdx1-csf@*":
    dependencies:
      "@babel/core": "*"
  "@storybook/telemetry@*":
    dependencies:
      react: ^18.0.0
      react-dom: ^18.0.0
  eslint-config-react-app@*:
    dependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

pnpEnableEsmLoader: true

pnpFallbackMode: dependencies-only

pnpMode: loose

yarnPath: .yarn/releases/yarn-3.2.2.cjs
